---
spring:
  application:
    name: apigw
  cloud:
    gateway:
      routes:
        - id: hello
          uri: lb://SERVICE-PROVIDER
          predicates:
            - Path=/hello/**
          filters:
            - authFilter=true
server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka